config/routes.rb
Lifesizer::Application.routes.draw do

  get "api/new"
  get "api/create"

  resources :user do
    resources :image, :controller => 'image_rest', :defaults => { :format => 'json' }
  end
  match '/user/:user_id/image', :to => 'image_rest#options', :constraints => {:method => 'OPTIONS'}, :defaults => { :format => 'json' }
  match '/user/:user_id/image/:id', :to => 'image_rest#options', :constraints => {:method => 'OPTIONS'}, :defaults => { :format => 'json' }
  match '/user/:user_id/prodimages/:id', :to => 'image_rest#product_images', :defaults => { :format => 'json' }

  match "google_search", :to => "google_search#index"
  match 'widget', :to => 'widget#index'
  get 'widget/popup'

  match '/view', :to => 'view#index'
  post '/view/screenres'
  match '/fview(.:format)/:guid(/:name)', :to => 'view#fullview'

  get "embed/index"
  get "embed/app_key"
  get "embed/instructions"
  get "embed/howto"

  get "admin/index"
  get "admin/images"
  match "admin/images/page/:page", :to => "admin#images"
  get "admin/users"
  get "admin/options"
  get "admin/screen_test"
  post "admin/api_options"
  post "admin/submit_options"

  get "admin/update_image_cache"
  get "admin/update_embed_cache"
  get "admin/update_bookmarklet_files"
  get "admin/update_shared_files"
  post "admin/sync_image_cache"
  post "admin/sync_bookmarklet"
  post "admin/become_user"
  match "admin/device_info"
  post "admin/change_featured"
  post "admin/change_private"
  delete "admin/delete_image"

  get "account/bookmarklet"
  get "account/home"

  match 'bmjs/:id.js', :to => 'custom_bookmarklets#script' # deprecated

  match 'bmc/:id.js', :to => 'custom_bookmarklets#script'
  resources :custom_bookmarklets

  get "plugin/customer/demo/(:id)-demo.user.js", :to => 'plugin#customer_demo', :constraints => { :id =>  /[^\/]+/ }
  get "plugin/customer/:id.user.js", :to => 'plugin#customer'

  get "test/show_cookies"
  post "test/delete_lifesize"
  post "test/delete_screen"

  get  "calibrate/start" # deprecated
  post "calibrate/done"  # deprecated

  post "calibrate/save"
  post "calibrate/save_known"

  get "configure/index"

  post "images/upload"
  get  "images/configure"
  post "images/configure"

  post "images/create_complete"

  get "images/recent"
  match "images/recent/page/:page", :to => 'images#recent'
  get "images/featured"
  get "images/popular"
  get "images/add_image"
  get "images/user"
  match "images/user/page/:page", :to => 'images#user'

  get "images/remote_save"
  get "images/remote_get"
  get "images/user_cache"

  post "images/add_image"

  post "images/add_step_1"
  post "images/add_finish"
  get "images/check_img"
  match 'lsc/:key.js', :to => 'images#check_img', :callback => 'imageRefCache.notify'

  resources :images

  get "home/index"

  get "demo/image"

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    match "/users/signed_up", :to => "registrations#complete", :controllers => {:registrations => "registrations"}, :as => "complete_user_registration", :via => :get
  end

  mount RailsAdmin::Engine => '/radmin', :as => 'rails_admin'

  root :to => "home#index"

end

app/views/admin/_imageinfo.html.erb
Title: <%= image.name %><br/>
Added: <%= distance_of_time_in_words(Time.now, image.created_at) %> ago <br/>
By: <%= image.user.email %><br/>
Source: <%= image.source || '' %><br/>
Featured: <%= (image.featured == 1) ? "yes" : "no" %><br/>
Private: <%= image.private ? "yes" : "no" %>

app/views/admin/device_info.html.erb
<% content_for :head do %>
  <%= javascript_include_tag google_jquery %>
<% end %>

<h1>device info</h1>

<p>Enter a name for this device and we'll save all its browser identification data</p>


<%= form_tag("/admin/device_info", :method => "post") do %>
  <%= label_tag(:q, "Device name") %>
  <%= text_field_tag(:name) %>
  <%= hidden_field_tag(:device_data) %>
  <%= submit_tag("send") %>
<% end %>


<p></p>
<pre>
<script type="text/javascript">
  // grab the interesting browser info
    function info(prop) {
        var ignore = ['plugins', 'mimeTypes'];
        var s = {};
        for (i in window[prop]) {
            if (ignore.indexOf(i) < 0) {
                s[i] = window[prop][i];
            }
        }
        return s;
    }
    function docBody() {
        var d = document.body;
        return {
            clientWidth:    d.clientWidth,
            clientHeight:   d.clientHeight,
            offsetWidth:    d.offsetWidth,
            offsetHeight:   d.offsetHeight
        };
    }

    function findPpi() {
        var a = 20; // lowest possible value
        var b = 1200; // highest possible value
        var x;
        if (!window.matchMedia || !window.matchMedia('(min-resolution: ' + a + 'dpi)').matches) {
            // min-resolution media query must not be supported
            return 0;
        }
        while (a < b - 1) {
            x = Math.round((a+b) / 2);
            var tst = window.matchMedia('(min-resolution: ' + x + 'dpi)').matches;
            //console.log("testing on " + x + ", result = " + tst);
            if (tst) {
                a = x;
            } else {
                b = x;
            }
        };
        return a;
    }

    var data = {
        outerWidth:         window.outerWidth,
        outerHeight:        window.outerHeight,
        innerWidth:         window.innerWidth,
        innerHeight:        window.innerHeight,
        'document.body':    docBody(),
        screen:             info('screen'),
        navigator:          info('navigator'),
        ppi:                findPpi(),
        devicePixelRatio:   window.devicePixelRatio
    }

    var json = (JSON != null) ? JSON.stringify(data, undefined, 2) : $.toJSON(data);
    document.writeln(json);
    $('#device_data').val(json);
</script>
</pre>

<br/>
<h2>Handset detection response</h2>
<pre>
  <%= @detect_data.to_yaml %>
</pre>

app/views/admin/images.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'admin/admin_images_require' %>
  <%= stylesheet_link_tag 'admin/images', :media => 'all' %>
<% end %>


<h2>Manage images</h2>

<% @images.each do |image| %>
<div class="image">
  <div class="thumbnail">
    <%= thumbnail(image, :type => :medium, :width => 150, :height => 150, :product_images => true) %>
    <%= link_to "full page view", full_image_view_path(image) %>
  </div>
  <div class="metadata" id="image_<%= image.id %>">
    Title: <%= image.name %><br/>
    Added: <%= distance_of_time_in_words(Time.now, image.created_at) %> ago <br/>
    By: <%= image.user.email %><br/>
    Source: <%= image.source || '' %><br/>
    Featured: <%= (image.featured == 1) ? "yes" : "no" %><br/>
    Private: <%= image.private ? "yes" : "no" %>
  </div>
  <div class="controls">
    <%= button_to "featured on/off", {:action => 'change_featured', :id => image }, {:remote => true, :method => :post }  %>
    <%= button_to "private on/off", {:action => 'change_private', :id => image }, {:remote => true, :method => :post }  %>
    <%= button_to "delete", {:action => 'delete_image', :id => image}, {:method => :delete, :confirm => 'are you sure you want to delete this image?' }  %>
    <br/>
    <%=  link_to "edit", edit_image_path(image) %> /
    <%=  link_to "demo page", :controller => :demo, :action => :image, :user => image.user, :ref => image.image_ref %>

  </div>
  <div class="clear"></div>
</div>
<% end %>

<nav id="page-nav">
  <a href="<%= next_page_url %>">next page</a>
</nav>

app/views/admin/index.html.erb
<a><h3><%= link_to "Rails admin", rails_admin_path %></h3></a>

<h2>Admin pages</h2>

<ul>
  <li><%= link_to 'Manage images', admin_images_path %></li>
  <li><%= link_to 'User management', admin_users_path %></li>
  <li><%= link_to 'Custom bookmarklets', custom_bookmarklets_path %></li>
</ul>



<h2>Demo utilities</h2>

<ul>
  <li><%= link_to 'Google search', :controller => 'google_search', :action => :index %></li>
  <li><%= link_to 'LifeSizer widget demo', '/demo/widget_test.html' %></li>
  <li><%= link_to 'GreaseMonkey demo script', '/demo/plugins/lifesizer.user.js' %></li>

  <!-- li>  link_to 'RubyLane script', '/demo/plugins/rubylane.user.js' </li -->
</ul>


<h2>Embed examples and tests</h2>
<ul>
  <li><%= link_to 'LifeSizer embed options demo', '/demo/embed/index.html' %></li>
</ul>


<h2>Test Pages</h2>

<ul>
  <li><%= link_to 'device info', :action => :device_info %></li>
  <li><%= link_to 'screen size test', :action => :screen_test %></li>
  <li><%= link_to 'lifesize cookies', test_show_cookies_path(:who => 'peter') %></li>
</ul>


<h2>CloudFiles</h2>

<ul>
  <li><%= link_to 'Update viewer assets', :action => :update_image_cache %></li>
  <li><%= link_to 'Update embed scripts', :action => :update_embed_cache %></li>
  <li><%= link_to 'Update bookmarklet files', :action => :update_bookmarklet_files %></li>
  <li><%= link_to 'Update shared WP/Rails assets', :action => :update_shared_files %></li>

</ul>

app/views/admin/options.html.erb
<% content_for :head do %>
  <style type="text/css">

table tr {
    height: 30px;
}
table tr td:first-child {
    width: 200px;
}

  </style>
<% end %>


<% if flash[:notice] %>
  <p><span style="color:blue;"><%= flash[:notice] %></span></p>
<% end  %>
<% if flash[:error] %>
  <p><span style="color:red;"><%= flash[:error] %></span></p>
<% end  %>

<h2><%= @user.email %></h2>


<table>
  <tr>
    <td>Most recent sign-in</td>
    <td><%= l @user.current_sign_in_at, :format => :long %></td>
  </tr>
</table>

<h4>API keys</h4>
<% read_key = api_read_key_for_user(@user) %>
<%= form_tag('/admin/api_options') do %>
<%= hidden_field_tag 'user', @user.id %>
<table>
  <tr>
    <td>read key</td>
    <td>
      <%= text_field_tag 'public_key', read_key %>
      <% if !read_key %>
        <%= submit_tag "create read key" %>
      <% end  %>
    </td>
  </tr>
  <tr>
    <td>write key</td>
    <td>
      <%= text_field_tag 'secret_key', api_write_key_for_user(@user) %>
      <% if !api_write_key_for_user(@user) %>
        <%= submit_tag "create secret key" %>
      <% end  %>
    </td>
  </tr>
  <tr>
    <td>domain name</td>
    <td>
      <%= text_field_tag 'hostname', api_hostname_for_user(@user) %>
    </td>
  </tr>
</table>
<%= submit_tag "save" %>
<% end %>

<h4>Bookmarklet</h4>
<%= form_tag('/admin/submit_options') do %>
<%= hidden_field_tag('user_id', @user.id) %>
<table>
  <tr>
    <td>drag to toolbar:</td>
    <td>
      <% if @account_option.bookmarklet? && @key %>
        <%=  render 'account/bm_code_js' %>
      <% else %>
        (enable bookmarklet visible and ensure write key exists)
      <% end %>
    </td>
  </tr>
  <tr>
    <td>bookmarklet visible</td>
    <td><%= check_box_tag 'visible', 'yes', @account_option.bookmarklet? %></td>
  </tr>
  <tr>
    <td>custom bookmarklet</td>
    <td><%= select_bookmarklet_tag(@custom_bookmarklets,@account_option.custom_bookmarklet) %>
    &nbsp;&nbsp;
      <%= submit_tag('edit bookmarklet script', :name => 'edit_bookmarklet') %>
    </td>
  </tr>
</table>
<p>
<%= submit_tag "save settings" %>
</p>

<% end %>

<%= link_to "manage bookmarklets", custom_bookmarklets_path %>


<hr/>
<h4>Browser plugin</h4>
<table>
  <tr>
    <td>has demo browser plugin</td>
    <td><%= has_demo_plugin ? "yes" : "no" %></td>
  </tr>
</table>

<hr/>

<p>
<% if @account_option.custom_bookmarklet %>
view bookmarklet cache
    <%= link_to "local", local_bookmarklet(api_write_key_for_user(@user)), :target => '_blank' %> /
    <%= link_to "in cloud", cloud_bookmarklet(api_write_key_for_user(@user)), :target => '_blank' %>
    <%= button_to "update bookmarklet cache", :action => 'sync_bookmarklet', :user_id => @user.id %>
<% end %>
</p>

<p>
view lifesizer cache
    <%= link_to "local", local_lifesizer_cache(api_read_key_for_user(@user)), :target => '_blank' %> /
    <%= link_to "in cloud", cloud_lifesizer_cache(api_read_key_for_user(@user)), :target => '_blank' %>
    <%= button_to "purge lifesizer cache", :action => 'sync_image_cache', :user_id => @user.id %>
</p>

<p>
  <%= link_to "back to users", :action => :users %>
</p>

app/views/admin/screen_test.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
	    <style type="text/css">

	html { height:100%; }
	body { height: 100%; margin:0; padding:0; overflow:auto;	
		   background-color: #ffffff; }   
//	#flashContent { display:none; }

	#coords {
		position: relative;
		font-size: 16px;
		font-weight: bold;
	}
	#coords div {
		position: absolute;
	}

	#screenWidth { top:45px; left:370px; color: #000000;}
	#screenHeight { top:250px; left:15px; color: #000000;}

	#availWidth { top:450px; left:320px; color: #760C7A;}
	#availHeight { top:250px; left:80px; color: #760C7A;}

	#innerWidth { top: 165px; left:	360px; color: #0F7024;}
	#innerHeight { top:	260px; left: 210px; color: #0F7024;}

	#windowWidth { top: 420px; left: 370px; color: #1325AA;}
	#windowHeight { top: 240px; left: 635px; color: #1325AA;}

	#browserZoom {
		top: 		240px;
		left:		330px;
		font-size:  30px;
		color: 		#0F7024;
	}

    .media-dpi-test {
        display: none;
    }

	   </style>
    <%= javascript_include_tag google_jquery, 'test/screen_test_require.js' %>

    <script type="text/javascript">

function innerDims() {
    var myWidth = 0, myHeight = 0;
    if (typeof (window.innerWidth) == 'number') {
         myWidth = window.innerWidth;
         myHeight = window.innerHeight;
    } else if (document.documentElement && (document.documentElement.clientWidth || document.documentElement.clientHeight)) {
         myWidth = document.documentElement.clientWidth;
         myHeight = document.documentElement.clientHeight;
    } else if (document.body && (document.body.clientWidth || document.body.clientHeight)) {
         myWidth = document.body.clientWidth;
         myHeight = document.body.clientHeight;
    }
    //console.log("x: " + myWidth + ", y: " + myHeight);
    return { w: myWidth, h: myHeight };
    /*
	var winW, winH;
	if (document.body && document.body.offsetWidth) {
	 winW = document.body.offsetWidth;
	 winH = document.body.offsetHeight;
	}
	if (document.compatMode == 'CSS1Compat' &&
	    document.documentElement &&
	    document.documentElement.offsetWidth ) {
	 winW = document.documentElement.offsetWidth;
	 winH = document.documentElement.offsetHeight;
	}
	if (window.innerWidth && window.innerHeight) {
	 winW = window.innerWidth;
	 winH = window.innerHeight;
	}
	return { w: winW, h: winH };
	*/
}

/** 
 * returns the outer dimensions of the current browser window. Note that this doesn't appear to work in IE
 */
function windowDims() {
    return { w: window.outerWidth, h: window.outerHeight };
}

/** 
 * returns the dimensions of the screen as reported by the JS layer. Note that in some browsers (FF, IE) this 
 * isn't the actual true screen resolution, as it is adjusted if the browser is zoomed in or out. 
 */
function screenDims() {
	return { w: screen.width, h: screen.height };
}

function availDims() {
	return { w: screen.availWidth, h:screen.availHeight };
}

function getParameterByName(name) {
  name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
  var regexS = "[\\?&]" + name + "=([^&#]*)";
  var regex = new RegExp(regexS);
  var results = regex.exec(window.location.search);
  if(results == null)
    return "";
  else
    return decodeURIComponent(results[1].replace(/\+/g, " "));
}

var zoom = 1.0;
var sd = new ScreenDetection();

function updateValues() {
	var screenDim = screenDims();
	$('.screen_width').html(screenDim.w);
	$('.screen_height').html(screenDim.h);

	var trueScreenDim = sd.trueScreenRes();
	$('.true_screen_width').html(trueScreenDim.w);
	$('.true_screen_height').html(trueScreenDim.h);

	var availDim = availDims();
	$('.avail_width').html(availDim.w);
	$('.avail_height').html(availDim.h);

    var innerDim = innerDims();
    $('.inner_width').html(innerDim.w);
    $('.inner_height').html(innerDim.h);

	var windowDim = windowDims();
	$('.window_width').html(windowDim.w);
	$('.window_height').html(windowDim.h);

	$('#percZoomLevel').html(Math.round(zoom*10000)/100);
    if (sd.canDetectZoom) {
      $('.zoomLevel').html(zoom);
    } else {
      $('.zoomLevel').html('cannot detect');
    }

    $('.deviceDPI').html(screen.deviceXDPI + " x " + screen.deviceYDPI);
    $('.logicalDPI').html(screen.logicalXDPI + " x " + screen.logicalYDPI);
    $('.systemDPI').html(screen.systemXDPI + " x " + screen.systemYDPI);

    $('.chromeZoom').html(window.outerWidth / window.innerWidth);

    $('.media_query_ppi').html(sd.findPpi());


}

function checkInnerDimensions(expectedWidth, expectedHeight) {
    var innerDim = innerDims();
    var msg = '';
    if (innerDim.w != expectedWidth) {
        msg += "inner width is " + Math.abs(innerDim.w - expectedWidth) + " pixels " + ((innerDim.w > expectedWidth) ? "greater" : "smaller") +
                " than expected width (" + expectedWidth + ")\n";
    }
    if (innerDim.h != expectedHeight) {
        msg += "inner height is " + Math.abs(innerDim.h - expectedHeight) + " pixels " + ((innerDim.h > expectedHeight) ? "greater" : "smaller") +
                " than expected height (" + expectedHeight + ")\n";
    }
    if (msg.length > 0) {
        alert(msg);
    } else {
        alert("inner dimensions correct");
    }
}

$(function() {

	window.onresize = updateValues;
	sd.watchZoom(function(obj) {
        zoom = obj.zoom;
		updateValues();
	});
    updateValues();

    if (!sd.canDetectZoom) {
        alert("unable to determine zoom level");
    }

    sd.watchScreenRes(function(width, height, init) {
        if (!init)
            alert('screen resolution has changed: ' + width + "x" + height);
    });

    var minScroll = 1000;
    var maxScroll = 0;
    $(document).mousewheel(function(event, delta) {
        $('#cur_scroll').attr('value', delta);
        var abs = Math.abs(delta);
        if (abs > 0 && abs < minScroll) {
            $('#min_scroll').attr('value', abs);
            minScroll = abs;
        }
        if (abs > maxScroll) {
            $('#max_scroll').attr('value', abs);
            maxScroll = abs;
        }
    });
    $('#resetButton').click(function() {
        $('#max_scroll,#min_scroll,#cur_scroll').attr('value', '');
        maxScroll = 0;
        minScroll = 1000;
    });

    $('#openButton').click(function() {
        var x = $('#resize_x').attr('value');
        var y = $('#resize_y').attr('value');
        var url = document.location.href + "?lsdebug=true&width=" + x + "&height=" + y;
        LsLog.info("opening window with dimensions " + x + "x" + y);
        LsWindow.open(url, x, y, { name: 'testwindow', scrollbars: true});
        //window.open (url, "testwindow","toolbar=no,scrollbars=yes,location=no,menubar=no,resizable=yes,width=" + x + ",height=" + y);
    });
    $('#resizeButton').click(function() {
        var x = parseInt($('#resize_x').attr('value'));
        var y = parseInt($('#resize_y').attr('value'));
        LsWindow.resizeTo(x,y);
        LsLog.debug('resizing window to ' + x + "x" + y);
        setTimeout(function() {
            checkInnerDimensions(x,y);
        }, 2000);
    });

    setTimeout(function() {
        var i = innerDims();
        LsLog.debug("inner dimensions: " + i.w + "x" + i.h);

        var expectedInnerWidth = parseInt(getParameterByName('width'));
        var expectedInnerHeight = parseInt(getParameterByName('height'));
        if (expectedInnerWidth && expectedInnerHeight) {
            checkInnerDimensions(expectedInnerWidth, expectedInnerHeight);
        }
    }, 1000);
});

   </script>
  </head>
  <body>
    
    <div id="coords">
      <%= image_tag "test/mac_screen.png" %>

	  <div id="screenWidth"  class="screen_width">?</div>
	  <div id="screenHeight" class="screen_height">?</div>

	  <div id="availWidth"  class="avail_width">?</div>
	  <div id="availHeight" class="avail_height">?</div>

   	  <div id="innerWidth"  class="inner_width">?</div>
   	  <div id="innerHeight" class="inner_height">?</div>

	  <div id="windowWidth"  class="window_width">?</div>
	  <div id="windowHeight" class="window_height">?</div>
	
	  <div id="browserZoom" class="value">zoom: <span id="percZoomLevel">?</span>%</div>
	</div>

    <div>
        <div style="float:left">
            <span class="value">Your javascript reported screen dimensions are <span class="screen_width">?</span> x <span class="screen_height">?</span></span> <br/>
           	<span class="value">Your true screen resolution is <span class="true_screen_width">?</span> x <span class="true_screen_height">?</span></span> <br/>
           	<span class="value">Your available space is <span class="avail_width">?</span> x <span class="avail_height">?</span></span><br/>
           	<span class="value">Your document dimensions are <span class="inner_width">?</span> x <span class="inner_height">?</span></span><br/>
           	<span class="value">Your window dimensions are <span class="window_width">?</span> x <span class="window_height">?</span></span><br/>
            <span class="value">Zoom level: <span class="zoomLevel">?</span></span><br/>
            <span class="value">Screen PPI based on media query: <span class="media_query_ppi">?</span></span><br/>
        </div>
        <div style="float:left;margin-left:40px">
            Window scroll:<br/>
            <input type="text" id="min_scroll" style="width:50px"/> min scroll  <br/>
            <input type="text" id="max_scroll" style="width:50px"/> max scroll <br/>
            <input type="text" id="cur_scroll" style="width:50px"/> current scroll<br/>
            <input type="button" value="reset" id="resetButton"/>
        </div>
    </div>
    <div style="clear:both"/>

    <br/>
    <div>
        <div style="float:left">
            <h3>windows</h3>
            <span class="value">Device DPI <span class="deviceDPI">?</span></span><br/>
            <span class="value">Logical DPI <span class="logicalDPI">?</span></span><br/>
            <span class="value">System DPI <span class="systemDPI">?</span></span><br/>
        </div>
        <div style="float:left;margin-left:40px">
            <p>Resize/open window: <br/>
            <input type="text" id="resize_x" style="width:50px"/> width
            <input type="text" id="resize_y" style="width:50px"/> height <br/>
            <input type="button" value="open in popup" id="openButton"/>
            <input type="button" value="resize" id="resizeButton"/></p>
        </div>
    </div>
    <div style="clear:both"/>

    <br/>
    <span class="value">chrome zoom calc <span class="chromeZoom">?</span></span><br/>
  </body>
</html>

app/views/admin/update_image.js.erb
$("#image_<%=@image.id%>").html("<%= escape_javascript(render(:partial => 'admin/imageinfo', :locals => { :image => @image })) %>");

app/views/admin/users.html.erb
<table border="2">
  <tr height="40">
    <th></th>
    <th><strong>email</strong></th>
    <th><strong>created</strong></th>
    <th><strong>plan</strong></th>
    <th><strong>options</strong></th>
  </tr>
  <% @users.reverse.each do |user| %>
  <tr height="30">
    <td width="40"><%= button_to(">", :action => 'become_user', :user_id => user.id) %></td>
    <td><% style = (current_user == user) ? 'style="color:blue;"' : '' %>
        <span <%= raw style %> ><%= user.email%></span>
    </td>
    <td width="130px"><%= user.created_at.to_formatted_s(:short)%></td>
    <td width="50"><%= AccountOption::PLANS[user.plan] %></td>
    <td><%= link_to("options", :action => :options, :id => user.id) %></td>
  </tr>
  <% end %>
</table>