config/routes.rb
Lifesizer::Application.routes.draw do

  get "api/new"
  get "api/create"

  resources :user do
    resources :image, :controller => 'image_rest', :defaults => { :format => 'json' }
  end
  match '/user/:user_id/image', :to => 'image_rest#options', :constraints => {:method => 'OPTIONS'}, :defaults => { :format => 'json' }
  match '/user/:user_id/image/:id', :to => 'image_rest#options', :constraints => {:method => 'OPTIONS'}, :defaults => { :format => 'json' }
  match '/user/:user_id/prodimages/:id', :to => 'image_rest#product_images', :defaults => { :format => 'json' }

  match "google_search", :to => "google_search#index"
  match 'widget', :to => 'widget#index'
  get 'widget/popup'

  match '/view', :to => 'view#index'
  post '/view/screenres'
  match '/fview(.:format)/:guid(/:name)', :to => 'view#fullview'

  get "embed/index"
  get "embed/app_key"
  get "embed/instructions"
  get "embed/howto"

  get "admin/index"
  get "admin/images"
  match "admin/images/page/:page", :to => "admin#images"
  get "admin/users"
  get "admin/options"
  get "admin/screen_test"
  post "admin/api_options"
  post "admin/submit_options"

  get "admin/update_image_cache"
  get "admin/update_embed_cache"
  get "admin/update_bookmarklet_files"
  get "admin/update_shared_files"
  post "admin/sync_image_cache"
  post "admin/sync_bookmarklet"
  post "admin/become_user"
  match "admin/device_info"
  post "admin/change_featured"
  post "admin/change_private"
  delete "admin/delete_image"

  get "account/bookmarklet"
  get "account/home"

  match 'bmjs/:id.js', :to => 'custom_bookmarklets#script' # deprecated

  match 'bmc/:id.js', :to => 'custom_bookmarklets#script'
  resources :custom_bookmarklets

  get "plugin/customer/demo/(:id)-demo.user.js", :to => 'plugin#customer_demo', :constraints => { :id =>  /[^\/]+/ }
  get "plugin/customer/:id.user.js", :to => 'plugin#customer'

  get "test/show_cookies"
  post "test/delete_lifesize"
  post "test/delete_screen"

  get  "calibrate/start" # deprecated
  post "calibrate/done"  # deprecated

  post "calibrate/save"
  post "calibrate/save_known"

  get "configure/index"

  post "images/upload"
  get  "images/configure"
  post "images/configure"

  post "images/create_complete"

  get "images/recent"
  match "images/recent/page/:page", :to => 'images#recent'
  get "images/featured"
  get "images/popular"
  get "images/add_image"
  get "images/user"
  match "images/user/page/:page", :to => 'images#user'

  get "images/remote_save"
  get "images/remote_get"
  get "images/user_cache"

  post "images/add_image"

  post "images/add_step_1"
  post "images/add_finish"
  get "images/check_img"
  match 'lsc/:key.js', :to => 'images#check_img', :callback => 'imageRefCache.notify'

  resources :images

  get "home/index"

  get "demo/image"

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    match "/users/signed_up", :to => "registrations#complete", :controllers => {:registrations => "registrations"}, :as => "complete_user_registration", :via => :get
  end

  mount RailsAdmin::Engine => '/radmin', :as => 'rails_admin'

  root :to => "home#index"

end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  before_filter :screen_config, :only => :image
  before_filter :lifesize, :only => :image

  # simply shows an image for demo purposes
  def image
    @image = Image.find_user_image_by_ref(params[:user], params[:ref])
  end
end

app/controllers/plugin_controller.rb
class PluginController < ApplicationController
  layout nil

  # customer browser plugins
  def customer
    render "#{params[:id]}.user.js", :content_type => 'text/javascript'
  end

  # customer browser plugins
  def customer_demo
    render "plugin/demo/#{params[:id]}.user.js", :content_type => 'text/javascript', :layout => '../plugin/demo/demo_plugin_layout'
  end
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/plugin_helper.rb
module PluginHelper

  def plugin_name
    api_hostname.split('.')[0]
  end

  def plugin_hostmatch
    "*://*.#{plugin_hostname}/*"
  end

  def plugin_hostname
    api_hostname
  end
end

app/views/plugin/demo/demo_plugin_layout.js.erb
// ==UserScript==
// @name           LifeSizer - <%= plugin_name %> demo
// @namespace      http://www.lifesizer.com/demo/<%= plugin_name %>
// @description    This demo adds LifeSizer capabilities to <%= plugin_hostname %>
// @match          <%= plugin_hostmatch %>
// ==/UserScript==

(function () {
    var LINK_TEXT = "view in life-size";
    var LS_LINK_ID = 'lsLink';

    // endpoints, set dynamically
    var HOST             = '<%= current_host %>';
    var CACHE_HOST       = '<%= cache_host %>';
    var ASSETS_HOST      = '<%= assets_host %>';
    // urls to embed script
    var EMBED_SCRIPT_URL     = '<%= embed_script_url(false)%>';
    var SSL_EMBED_SCRIPT_URL = '<%= embed_script_url(true)%>';
    var BOOKMARKLET_URL      = '<%= bookmarklet_url %>';

    var bookmarkletLoaded = false;

    // return window object - this works both in Greasemonkey scripts and Chrome plugins
    var win = (function(){
        var a;
        try {
            a = unsafeWindow === window ? false : unsafeWindow;
        } finally {
            return a || (function(){
                var e = document.createElement('p');
                e.setAttribute('onclick', 'return window;');
                return e.onclick();
            }());
        }
    }());

    var handlers = [];
    var handler;

	// this is where the thinkgeek specific stuff goes
	handlers.push(
        <%= yield %>
    );


    /**
     * creates a DIV element containing the LifeSizer link, and returns this DIV element. Caller is
     * responsible for adding this element to the DOM and positioning it.
     * @param ref image ref
     * @param altImageUrl (optional) image url, if a variation of the original image should be used instead
     * @return DOM element of link
     */
    function createLifeSizerLinkElem(ref, altImageUrl) {
        //var u = (typeof(altImageUrl) == 'string') ? (' data-ls-url="'+altImageUrl+'"') : '';
        var elem = document.createElement('div');
        var imgUrl = 'http://' + ASSETS_HOST + '/img/button/asw_lifesizer30.png';

        elem.id = LS_LINK_ID;
        elem.setAttribute('data-ls-ref', ref);
        if (typeof(altImageUrl) == 'string') {
            elem.setAttribute('data-ls-imgurl', altImageUrl);
        }
        elem.style.position = 'absolute';
        elem.style.width = '182px';
        //elem.style.height = '40px';
        //elem.style.paddingLeft = '45px';
        //elem.style.textAlign = 'left';
        //elem.style.background = 'url("http://' + ASSETS_HOST + '/img/logo/ls_icon_gray40.png") no-repeat';

        elem.style.display = 'none'; // hide by default
        elem.innerHTML = '<img src="' + imgUrl + '" width="182" height="30" />';

        //elem.innerHTML = '<a href="#" style="font-size:15px;line-height:40px;vertical-align:middle;">' + LINK_TEXT + '</a>';
        return elem;
    }

    /**
     * finds the correct implementation for the current domain
     * @return implementation handler for current domain
     */
    function findHandler() {
        var domain = document.domain;
        for (var i=0; i<handlers.length; i++) {
            var p = new RegExp(handlers[i].domain);
            if (p.test(domain)) {
				return handlers[i];
            }
        }
		return null; // no match
    }

    // initialize plugin, add links and set up click handlers
    setTimeout(function () {

        GM_log("initializing plugin");

        jQuery = win.jQuery;

        handler = findHandler();
        if (handler) {
            // initialize
            handler.init();

            // initialize configure image plugin
            initImageConfigure();

            // start calibration on ctrl-l
            setShortCutHandler();

            if (handler.isValidPage()) {
                // embed the lifesizer script
                embedLsScript(handler);
                //alert("running LifeSizer plugin for domain: " + handler.domain + " ref: " + handler.getRef());
            }
       }
    }, 500);

    /**
     * embed the LifeSizer script
     */
    function embedLsScript(handler) {
        var lsOptions = {
            appKey: handler.appKey,
            user: handler.lsUser,
            serverCheck: true,
            host: HOST,
            lsCacheHost: CACHE_HOST,
            changeVisibility: false
        };
        if (handlerDefines('lifesizable'))
            lsOptions.notifyImages = handler.lifesizable;
        win.lsAsyncInit = function() {
          win.Ls.init(lsOptions);
        };
        (function() {
          var s = document.createElement('script'); s.async = true;
          s.type = 'text/javascript';
          s.src = ('http:' == document.location.protocol) ? EMBED_SCRIPT_URL : SSL_EMBED_SCRIPT_URL;
          var x = document.getElementsByTagName('script')[0];
          x.parentNode.insertBefore(s, x);
        }());
    }

    // returns true if handlers defines a function with given name
    function handlerDefines(name) {
        return typeof(handler[name]) == 'function';
    }

    function initImageConfigure() {
        win._lsv={ appKey: handler.appWriteKey, c:3, host: HOST };
    }

    /**
     * start the image configuration
     */
    function doImageConfigure() {
        if (!bookmarkletLoaded) {
            // load bookmarklet script
            bookmarkletLoaded = true;
            var s=document.createElement('script');
            s.setAttribute('type','text/javascript');
            s.setAttribute('charset','UTF-8');
            s.setAttribute('src', BOOKMARKLET_URL);
            document.getElementsByTagName('head')[0].appendChild(s);
        } else {
            // bookmarklet has already been loaded.
            win.LsBookmarklet.start();
        }
    }

    /**
     * attaches the ctrl-L key stroke handler to initiate the image calibration
     */
	function setShortCutHandler() {
		var isCtrl = false;
		function keyup(e) {
			if (e.which == 17) isCtrl=false;
		}
		function keydown(e) {
			if(e.which == 17) isCtrl=true;
			if(e.which == 76 && isCtrl == true) {
                doImageConfigure();
				return false;
			}
		}
		document.addEventListener("keyup", keyup, true);
		document.addEventListener("keydown", keydown, true);
	}
})();
// end