config/routes.rb
Lifesizer::Application.routes.draw do

  get "api/new"
  get "api/create"

  resources :user do
    resources :image, :controller => 'image_rest', :defaults => { :format => 'json' }
  end
  match '/user/:user_id/image', :to => 'image_rest#options', :constraints => {:method => 'OPTIONS'}, :defaults => { :format => 'json' }
  match '/user/:user_id/image/:id', :to => 'image_rest#options', :constraints => {:method => 'OPTIONS'}, :defaults => { :format => 'json' }
  match '/user/:user_id/prodimages/:id', :to => 'image_rest#product_images', :defaults => { :format => 'json' }

  match "google_search", :to => "google_search#index"
  match 'widget', :to => 'widget#index'
  get 'widget/popup'

  match '/view', :to => 'view#index'
  post '/view/screenres'
  match '/fview(.:format)/:guid(/:name)', :to => 'view#fullview'

  get "embed/index"
  get "embed/app_key"
  get "embed/instructions"
  get "embed/howto"

  get "admin/index"
  get "admin/images"
  match "admin/images/page/:page", :to => "admin#images"
  get "admin/users"
  get "admin/options"
  get "admin/screen_test"
  post "admin/api_options"
  post "admin/submit_options"

  get "admin/update_image_cache"
  get "admin/update_embed_cache"
  get "admin/update_bookmarklet_files"
  get "admin/update_shared_files"
  post "admin/sync_image_cache"
  post "admin/sync_bookmarklet"
  post "admin/become_user"
  match "admin/device_info"
  post "admin/change_featured"
  post "admin/change_private"
  delete "admin/delete_image"

  get "account/bookmarklet"
  get "account/home"

  match 'bmjs/:id.js', :to => 'custom_bookmarklets#script' # deprecated

  match 'bmc/:id.js', :to => 'custom_bookmarklets#script'
  resources :custom_bookmarklets

  get "plugin/customer/demo/(:id)-demo.user.js", :to => 'plugin#customer_demo', :constraints => { :id =>  /[^\/]+/ }
  get "plugin/customer/:id.user.js", :to => 'plugin#customer'

  get "test/show_cookies"
  post "test/delete_lifesize"
  post "test/delete_screen"

  get  "calibrate/start" # deprecated
  post "calibrate/done"  # deprecated

  post "calibrate/save"
  post "calibrate/save_known"

  get "configure/index"

  post "images/upload"
  get  "images/configure"
  post "images/configure"

  post "images/create_complete"

  get "images/recent"
  match "images/recent/page/:page", :to => 'images#recent'
  get "images/featured"
  get "images/popular"
  get "images/add_image"
  get "images/user"
  match "images/user/page/:page", :to => 'images#user'

  get "images/remote_save"
  get "images/remote_get"
  get "images/user_cache"

  post "images/add_image"

  post "images/add_step_1"
  post "images/add_finish"
  get "images/check_img"
  match 'lsc/:key.js', :to => 'images#check_img', :callback => 'imageRefCache.notify'

  resources :images

  get "home/index"

  get "demo/image"

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    match "/users/signed_up", :to => "registrations#complete", :controllers => {:registrations => "registrations"}, :as => "complete_user_registration", :via => :get
  end

  mount RailsAdmin::Engine => '/radmin', :as => 'rails_admin'

  root :to => "home#index"

end

app/models/custom_bookmarklet.rb
class CustomBookmarklet < ActiveRecord::Base
  has_many :account_options
  has_many :users, :through => :account_options
end

app/controllers/custom_bookmarklets_controller.rb
class CustomBookmarkletsController < ApplicationController
  before_filter :authenticate_admin!, :except => 'script'

  # GET /custom_bookmarklets
  # GET /custom_bookmarklets.xml
  def index
    @custom_bookmarklets = CustomBookmarklet.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @custom_bookmarklets }
    end
  end

  # GET /custom_bookmarklets/1
  # GET /custom_bookmarklets/1.xml
  def show
    @custom_bookmarklet = CustomBookmarklet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @custom_bookmarklet }
    end
  end

  # GET /custom_bookmarklets/new
  # GET /custom_bookmarklets/new.xml
  def new
    @custom_bookmarklet = CustomBookmarklet.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @custom_bookmarklet }
    end
  end

  # GET /custom_bookmarklets/1/edit
  def edit
    @custom_bookmarklet = CustomBookmarklet.find(params[:id])
    @users = @custom_bookmarklet.users
  end

  # POST /custom_bookmarklets
  # POST /custom_bookmarklets.xml
  def create
    @custom_bookmarklet = CustomBookmarklet.new(params[:custom_bookmarklet])

    respond_to do |format|
      if @custom_bookmarklet.save
        format.html { redirect_to(@custom_bookmarklet, :notice => 'Custom bookmarklet was successfully created.') }
        format.xml  { render :xml => @custom_bookmarklet, :status => :created, :location => @custom_bookmarklet }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @custom_bookmarklet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /custom_bookmarklets/1
  # PUT /custom_bookmarklets/1.xml
  def update
    @custom_bookmarklet = CustomBookmarklet.find(params[:id])

    respond_to do |format|
      if @custom_bookmarklet.update_attributes(params[:custom_bookmarklet])
        format.html { redirect_to(@custom_bookmarklet, :notice => 'Custom bookmarklet was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @custom_bookmarklet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /custom_bookmarklets/1
  # DELETE /custom_bookmarklets/1.xml
  def destroy
    @custom_bookmarklet = CustomBookmarklet.find(params[:id])
    @custom_bookmarklet.destroy

    respond_to do |format|
      format.html { redirect_to(custom_bookmarklets_url) }
      format.xml  { head :ok }
    end
  end

  # loads and returns a custom bookmarklet script
  def script
    key = params[:id]

    script = nil
    if key
      api_key = ApiKey.check_valid_key_for_write(key)
      if api_key
        ao = api_key.user.account_option
        script = ao.custom_bookmarklet.script if ao.custom_bookmarklet
      else
        logger.info("no valid key")
      end
    end

    if script
      render :js => script
    else
      render :status => 404, :nothing => true
    end
  end
end

app/helpers/custom_bookmarklets_helper.rb
module CustomBookmarkletsHelper
end

app/views/custom_bookmarklets/_form.html.erb
<%= form_for(@custom_bookmarklet) do |f| %>
  <% if @custom_bookmarklet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@custom_bookmarklet.errors.count, "error") %> prohibited this custom_bookmarklet from being saved:</h2>

      <ul>
      <% @custom_bookmarklet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :script %><br />
    <%= f.text_area :script, :style => "width:900px;height: 400px;font-family: monospace;font-size: 12px" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/custom_bookmarklets/edit.html.erb
<h2>Edit bookmarklet</h2>

<% if !@users %>
    <p>This bookmarklet is not yet associated to any accounts</p>
<% else %>
    <p>This bookmarklet is used by the following users:
      <ul>
        <% @users.each do |u| %>
            <li><%= u.email %></li>
        <% end %>
      </ul>
    </p>
<% end %>

<%= render 'form' %>

<%= link_to 'Show', @custom_bookmarklet %> |
<%= link_to 'Back', custom_bookmarklets_path %>

app/views/custom_bookmarklets/index.html.erb
<h2>Bookmarklets</h2>

<table>

<% @custom_bookmarklets.each do |custom_bookmarklet| %>
  <tr width="800">
    <td width="500"><%= custom_bookmarklet.name %></td>
    <td style="padding:10px"><%= link_to 'Show', custom_bookmarklet %></td>
    <td style="padding:10px"><%= link_to 'Edit', edit_custom_bookmarklet_path(custom_bookmarklet) %></td>
    <td style="padding:10px"><%= link_to 'Delete', custom_bookmarklet, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Custom bookmarklet', new_custom_bookmarklet_path %>

app/views/custom_bookmarklets/new.html.erb
<h1>New custom_bookmarklet</h1>

<%= render 'form' %>

<%= link_to 'Back', custom_bookmarklets_path %>

app/views/custom_bookmarklets/show.html.erb
<p id="notice"><%= notice %></p>

<p>

<h4><%= @custom_bookmarklet.name %></h4>

<textarea disabled='true' style="width:900px;height: 400px;font-family: monospace;font-size: 12px">
<%= @custom_bookmarklet.script.strip%>
</textarea>
</p>

<%= link_to 'Edit', edit_custom_bookmarklet_path(@custom_bookmarklet) %> |
<%= link_to 'Back', custom_bookmarklets_path %>