config/routes.rb
Lifesizer::Application.routes.draw do

  get "api/new"
  get "api/create"

  resources :user do
    resources :image, :controller => 'image_rest', :defaults => { :format => 'json' }
  end
  match '/user/:user_id/image', :to => 'image_rest#options', :constraints => {:method => 'OPTIONS'}, :defaults => { :format => 'json' }
  match '/user/:user_id/image/:id', :to => 'image_rest#options', :constraints => {:method => 'OPTIONS'}, :defaults => { :format => 'json' }
  match '/user/:user_id/prodimages/:id', :to => 'image_rest#product_images', :defaults => { :format => 'json' }

  match "google_search", :to => "google_search#index"
  match 'widget', :to => 'widget#index'
  get 'widget/popup'

  match '/view', :to => 'view#index'
  post '/view/screenres'
  match '/fview(.:format)/:guid(/:name)', :to => 'view#fullview'

  get "embed/index"
  get "embed/app_key"
  get "embed/instructions"
  get "embed/howto"

  get "admin/index"
  get "admin/images"
  match "admin/images/page/:page", :to => "admin#images"
  get "admin/users"
  get "admin/options"
  get "admin/screen_test"
  post "admin/api_options"
  post "admin/submit_options"

  get "admin/update_image_cache"
  get "admin/update_embed_cache"
  get "admin/update_bookmarklet_files"
  get "admin/update_shared_files"
  post "admin/sync_image_cache"
  post "admin/sync_bookmarklet"
  post "admin/become_user"
  match "admin/device_info"
  post "admin/change_featured"
  post "admin/change_private"
  delete "admin/delete_image"

  get "account/bookmarklet"
  get "account/home"

  match 'bmjs/:id.js', :to => 'custom_bookmarklets#script' # deprecated

  match 'bmc/:id.js', :to => 'custom_bookmarklets#script'
  resources :custom_bookmarklets

  get "plugin/customer/demo/(:id)-demo.user.js", :to => 'plugin#customer_demo', :constraints => { :id =>  /[^\/]+/ }
  get "plugin/customer/:id.user.js", :to => 'plugin#customer'

  get "test/show_cookies"
  post "test/delete_lifesize"
  post "test/delete_screen"

  get  "calibrate/start" # deprecated
  post "calibrate/done"  # deprecated

  post "calibrate/save"
  post "calibrate/save_known"

  get "configure/index"

  post "images/upload"
  get  "images/configure"
  post "images/configure"

  post "images/create_complete"

  get "images/recent"
  match "images/recent/page/:page", :to => 'images#recent'
  get "images/featured"
  get "images/popular"
  get "images/add_image"
  get "images/user"
  match "images/user/page/:page", :to => 'images#user'

  get "images/remote_save"
  get "images/remote_get"
  get "images/user_cache"

  post "images/add_image"

  post "images/add_step_1"
  post "images/add_finish"
  get "images/check_img"
  match 'lsc/:key.js', :to => 'images#check_img', :callback => 'imageRefCache.notify'

  resources :images

  get "home/index"

  get "demo/image"

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    match "/users/signed_up", :to => "registrations#complete", :controllers => {:registrations => "registrations"}, :as => "complete_user_registration", :via => :get
  end

  mount RailsAdmin::Engine => '/radmin', :as => 'rails_admin'

  root :to => "home#index"

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # authentication required for most actions in this controller
  before_filter :authenticate_user! , :except => [:featured, :recent, :show, :remote_save, :remote_get, :check_img]
  # authentication for jsonp request
  before_filter :json_auth_check_for_write, :only => [:remote_save, :remote_get]
  before_filter :json_auth_check_for_read,  :only => [:check_img]

  before_filter :screen_config, :only => [:index, :show, :edit, :featured, :recent, :add_image, :user, :create_complete]
  before_filter :lifesize, :only => [:index, :show, :edit, :featured, :recent, :user, :create_complete]

  VALIDATION_ERROR = 1

  # GET /images
  # GET /images.xml
  def index
    @images = Image.find_images

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @images }
    end
  end

  # returns the featured LifeSize images.
  def featured
    @images = Image.featured_images
  end

  # returns the 100 most recently added images.
  def recent
    page = params[:page].try(:to_i) || 1
    @images = Image.recent_images(page)
  end

  # fetches and displays all images submitted by the current user
  def user
    page = params[:page].try(:to_i) || 1
    @images = Image.user_images(current_user.id, page)
  end

  # GET /images/17838978a3ec983b18ff
  # GET /images/17838978a3ec983b18ff.xml
  def show
    @image = Image.find_by_guid(params[:id])

    return not_found if !@image

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @image }
    end
  end

  #
  # renders the new Image screen
  def new
    @image = Image.new

    @has_custom_bookmarklet = current_user.account_option.bookmarklet?
    if @has_custom_bookmarklet
      @api_key = ApiKey.find_write_key(current_user)
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # POST
  # receives the image upload or the remote image url
  def upload
    @image = Image.new(params[:image])

  end

  # GET /images/1/edit
  def edit
    @image = Image.editable_by(current_user).find_by_guid(params[:id])
    return not_found if !@image
  end

  #
  # handles the upload url form post
  def create
    valid = false
    begin
      par = params[:image].except(:remote_upload_url, :width, :height, :medium_height, :medium_width)
      @image = Image.new(par)
      @image.user = current_user
      @image.remote_upload_url = params[:image][:remote_upload_url]
      @image.original_url = @image.remote_upload_url if has_value(@image.remote_upload_url)
      @image.page_url = params[:image][:page_url] if !params[:image][:page_url].blank?
      @image.width = params[:image][:width] if @image.width.nil?
      @image.height = params[:image][:height] if @image.height.nil?
      @image.medium_width = params[:image][:medium_width] if @image.medium_width.nil?
      @image.medium_height = params[:image][:medium_height] if @image.medium_height.nil?
      # validate image
      valid = @image.valid?
    rescue CarrierWave::DownloadError
      @image.errors.add(:remote_upload_url, "^This url doesn't appear to be valid")
    rescue CarrierWave::IntegrityError
      @image.errors.add(:remote_upload_url, "^This url does not appear to point to a valid image")
    end

    # only validate, don't save yet
    if valid
      # calculate best render dimensions for image
      if params['browser_width'] && params['browser_height']
        max_width = params['browser_width'].to_i - 50
        max_height = params['browser_height'].to_i - 50
      else
        logger.warn("no browser_width or browser_height set")
        max_width = 800
        max_height = 600
      end

      render_dims = ScreenUtils.calculate_biggest_display_dimensions_possible(@image, max_width, max_height)
      @render_width, @render_height = render_dims[0], render_dims[1]

      logger.debug("rendering image of #{@image.width}x#{@image.height} at res #{@render_width}x#{@render_height}" +
        " to fit browser of dims #{max_width}x#{max_height}")

      @scale = 100
      render :action => :configure, :layout => "layouts/configure"
      # redirect_to(images_configure_path)
    else
      
      render :action => :new
    end
  end

  # parses the config data and completes the image creation
  
  def create_complete
    @image = Image.new(params[:image])
    @image.user = current_user

    # calculate the image dpi.
    length_in_inches = @image.length_in_inches
    @image.ppi = @lifesize.calc_image_ppi_with_arrow(params['arrow_length'].to_f, length_in_inches, @image.width, params['render_width'].to_i)
    @image.calibrate_data(params['arrow_start'], params['arrow_end'])
    @image.image_type = Image::TYPE_LS
    @image.source = 'site'

    if @image.save
      redirect_to(images_user_path)
    else
      render :action => :new
    end
  end

  #
  # renders page 2 of the image add flow
  def configure
  end


  # PUT /images/1
  # PUT /images/1.xml
  #
  # only the following properties can be updated:
  #   calibrate_length
  #   calibrate_unit
  #   calibrate_coords
  #   page_url
  #   original_url
  #   ref
  #   private
  #
  # image is identified by the auto_ref (like '_12')
  def update
    par = params

    @image = Image.editable_by(current_user).find_by_guid(params[:guid])

    # set these variables back to nil if they were in the request but blank
    if par[:ref]
      @image.ref = par[:ref].blank? ? nil : par[:ref]
    end
    if par[:name]
      @image.name = par[:name].blank? ? nil : par[:name]
    end
    if par[:page_url]
      @image.page_url = par[:page_url].blank? ? nil : par[:page_url]
    end
    @image.private = par[:private] if par[:private]

    if !par[:calibrateLength].blank?
      @image.calibrate_length = par[:calibrateLength].to_f
      @image.calibrate_unit   = par[:calibrateUnit].to_i if !par[:calibrateUnit].blank?
      @image.calibrate_coords = par[:calibrateCoords] if !par[:calibrateCoords].blank?
      @image.ppi = calculate_ppi(@image)
    end

    orig_url = par[:originalUrl]
    if !orig_url.blank? && orig_url != @image.original_url
      # url was updated
      @image.remote_upload_url = orig_url
      @image.original_url = orig_url
    end

    if @image.save
      render :json => @image.js_serialize
    else
      #TODO: handle error
      render :json => { :error => 500 }, :status => 500
    end
  end

  # PUT /images/1
  # PUT /images/1.xml
  def updateold
    puts "UPDATING IMAGE"
    img = params[:image]

    @image = Image.find_user_image(current_user.id, params[:id]).first

    if @image.original_url != img[:original_url]
      #image url has changed
      puts "IMAGE URL has changed!"
      begin
        @image.remote_upload_url = img[:original_url]
      rescue => err
        #TODO: url could not be fetched, return error
      end
    end

    # only allow the following attributes to be updated, and set any blank values to nil
    attr = img.select { |k, v| [:original_url, :name, :page_url, :ref, :private].include?(k.to_sym)}
    update_attr = {}
    attr.each_pair { |k,v| update_attr[k] = v.blank? ? nil : v }

    respond_to do |format|
      if @image.update_attributes(update_attr)
        format.html { redirect_to(@image, :notice => 'Image was successfully updated.') }
        format.xml  { head :ok }
        format.js { render :json => { :response => 'success'} }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
        format.js { render :nothing => true }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.xml
  def destroy
    @image = Image.editable_by(current_user).find_by_guid(params[:id])
    return not_found if !@image
    @image.destroy

    respond_to do |format|
      format.html { redirect_to(images_user_path) }
      format.xml  { head :ok }
    end
  end

  # main add image page
  def add_image
     @image = Image.new
     @ppi = @screen_config[:ppi]
  end

  # receives the image url, then goes out to fetch that url and returns the image thumbnail
  # url and other data
  def add_step_1
     image_url = params[:input_image_url]
     begin
       raise "no image url" if params[:input_image_url].empty?
       data = ImageTool.fetch_and_make_temp_thumbnail(image_url)
       data[:success] = true
     rescue => err
       data = { :success => false }
       logger.error("unable to fetch image or create thumbnail: #{err}")
     end
     render :json => data
  end

  # finishes the image add steps - receives all data required to create and save the lifesize image
  def add_finish
    if !current_user
      redirect_to_error("you are not logged in. Please log in first")
      return
    end

    @image = Image.new(params[:image])
    @image.ref = nil if @image.ref.nil? || @image.ref.empty?
    @image.name = nil if @image.name.nil? || @image.name.empty?
    @image.description = nil if @image.description.nil? || @image.description.empty?

    # create a lifesize instance, needed to calculate DPI
    lifesize = LifeSize.new(screen_config)

    # calculate the image dpi.
    cd = ActiveSupport::JSON.decode(params[:configure_data])
    length_inches = cd['unit'] == 'cm' ? (cd['physLength']/2.54) : cd['physLength']
    @image.ppi = lifesize.calc_image_ppi_with_arrow(cd['pixLength'], length_inches, @image.width, cd['renderWidth'])
    @image.calibrate_data=cd
    @image.user = current_user
    @image.image_type = Image::TYPE_LS

    logger.info("PPI of new image is: #{@image.ppi}")
    finish = (params['finish'] == 'true')

    #save the image
    resp = { :success => false }
    #begin
      if @image.save
         # move the temporary thumbnail url to it's permanent location
         ImageTool.save_thumbnail(params[:thumbnail_url], @image)
         resp[:success] = true
         resp[:redirect_to] = finish ? images_user_path : url_for(:action => :add_image)
      end

app/helpers/images_helper.rb
module ImagesHelper

  # used by image configure to render lifesize image for calibration. Note that this won't be displayed at
  # actual size. It will generally be displayed at the largest possible size for the current browser window,
  # to make calibration easier
  def lifesize_new_image(image, render_width, render_height, scale, options)
    render_lifesize_image(image.url, image.width, image.height, render_width, render_height, options, scale)
  end

  # returns the url for the next page
  def next_page_url
    current_page = params[:page].try(:to_i) || 1
    if request.path.match /\/page\/(\d+)/
       request.path.gsub(/\/page\/(\d+)$/, "/page/#{current_page+1}")
    else
      "#{request.path}/page/#{current_page+1}"
    end
  end

  def image_source(image)
    if !image.original_url.blank?
      link_to(truncate_middle(image.original_url, 60), image.original_url)
    else
      "uploaded"
    end
  end

  # returns title of image for social sharing (disqus, facebook, etc)
  def social_title(image)
    name = image.name
    if !name.blank?
      name
    elsif domain = product_domain(image)
      "LifeSizer image on #{domain}"
    else
      "LifeSizer image"
    end
  end

  private

  def truncate_middle(str, len)
    if str.length > (len - 3)
      s = len / 2
      str[0,s-2] + "..." + str[-(s-2), (s-2)]
    else
      str
    end
  end
end

app/views/images/_form.html.erb
<%= form_for [current_user, @image], :remote => true do |f| %>
  <div id="error_explanation">
    <h2>there were some problems with your form data. Please fix below... </h2>
  </div>

  <div id="columns">
    <div class="column">
      <div id="url" class="field">
        <%= f.label :original_url, "Image URL" %><br />
        <div class="error_label err_remote_upload_url"></div>
        <%= f.text_field :original_url %>
      </div>
      <div id="name" class="field">
        <%= f.label :name, "Name" %><br />
        <div class="error_label err_name"></div>
        <%= f.text_field :name %>
      </div>
      <div id="page_url" class="field">
        <%= f.label :page_url, "Page URL" %><br />
        <div class="error_label err_page_url"></div>
        <%= f.text_field :page_url %>
      </div>
      <div id="ref" class="field">
        <%= f.label :ref, "Image Reference" %><br />
        <div class="error_label err_ref"></div>
        <%= f.text_field :ref %>
      </div>
      <div id="private" class="field">
        <%= f.check_box :private %>
        <%= f.label :private, "Keep private" %>
      </div>

      <div class="actions">
        <%= f.submit 'calibrate image', :id => "calibrate_button", :class => "blue-button" %>
        <%= f.submit 'save', :id => 'save_button', :class => 'blue-button' %>
        <%= f.submit 'save and next', :id => 'save_next_button', :class => 'blue-button' %>
      </div>
    </div><!-- end left column -->
    <div class="column"><!-- begin right column -->
      <%= thumbnail(@image, :type => :medium, :product_images => true) %>
    </div>
  </div>
  <div class="clear"></div>
<% end %>

app/views/images/_image_tile.html.erb
<div class="ls_item">
  <%= thumbnail(image, :type => :medium, :width => 200, :height => 400, :product_images => product_images) %>
  <div class="metadata">
    <% if (!compact || !image.name.blank? || !image.page_url.blank?) %>
    <div>
      <% if !image.name.blank? %>
        <span class='name'><%= image.name %></span><br/>
      <% end %>
      <% if !image.page_url.blank? %>
        <span class='page_url'><%= link_to "view on #{product_domain(image)}", image.page_url, :target => '_blank' %></span><br/>
      <% end %>
      <% if !compact %>
      created: <%= distance_of_time_in_words(Time.now, image.created_at) %> ago
      <% end %>
    </div>
    <% if !compact %>
    <div class="buttons">
      <%= warning_icon(image) %>
      <a class="embed-link" href="javascript:showEmbed(<%=image.user_id%>,'<%=image.image_ref%>');" title="embed instructions"><img src="/img/galleries/embed_share.png" /></a>
      <%= link_to(image_tag("/img/galleries/edit.png", :size => "16x16", :title => 'Edit'), edit_image_path(image)) %>
      <%= link_to(image_tag("/img/galleries/delete.png", :size => "16x16", :title => 'Delete'), image_path(image), :method=>:delete, :confirm=>"Are you sure you want to delete this image?") %>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/images/_thumbnail.html.erb
<img src="<%= thumbnail[:thumbnail_url] %>" height="<%= thumbnail[:thumb_height] %>" width="<%= thumbnail[:thumb_width] %>" />

app/views/images/configure.html.erb
<% title "Calibrate your image" %>

<div class="stretchedToBrowserWindow">
  <h2>Calibrate your image</h2>

  <!-- dialog contents -->
  <div id="dialogs" style="display:none">
    <div id="initMsg">
      Please click and drag on any part of the image to draw a line for which you know the actual dimensions.
      (ie. if you know the width, draw a line from the left edge to the right edge of the object in your image)
    </div>
    <div id="sizePrompt">
      <p>Please tell us the actual length of the arrow you've drawn, in inches or centimeters.</p>
      <input type="text" id="arrowSize" name="arrowSize" size="5"/>
      <select name="unit">
        <option value="in">inches</option>
        <option value="cm">cm</option>
        <option value="mm">mm</option>
      </select>
    </div>
  </div>

  <%= form_for @image, :url => images_create_complete_path(@image), :html => {:multipart => true, :class => 'lsform' } do |f| %>
    <%= f.hidden_field :upload_cache %>
    <%= f.hidden_field :original_url %>
    <%= f.hidden_field :page_url %>
    <%= f.hidden_field :width %>
    <%= f.hidden_field :height %>
    <%= f.hidden_field :medium_width %>
    <%= f.hidden_field :medium_height %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :ref %>
    <%= f.hidden_field :input_length %>
    <%= f.hidden_field :unit %>
    <!-- the following are not model properties, so use regular input fields -->
    <input type="hidden" id="arrow_start" name="arrow_start"/>
    <input type="hidden" id="arrow_end" name="arrow_end"/>
    <input type="hidden" id="arrow_length" name="arrow_length"/>
    <input type="hidden" id="render_width" name="render_width"/>
    <input type="hidden" id="render_height" name="render_height"/>
  <% end %>

  <div id="toolbar">
    <div class="text">zoom out</div>
    <div id="slider"></div>
    <div class="text">zoom in</div>
    <div class="navButton"><button id="finishButton">finish</button></div>
    <div class="navButton"><button id="backButton">go back</button></div>
  </div>

  <div id="imageContainer">
    <%= lifesize_new_image(@image, @render_width, @render_height, @scale, :id => 'mainLifeSizeImg' ) %>
    <div id="arrMsg" style="display:none"><div id="sizeLabel"></div></div>
  </div>
</div>

app/views/images/edit.html.erb
<% content_for :head do %>
  <%= javascript_include_tag :images_edit %>
  <%= stylesheet_link_tag :images_edit, :media => 'all' %>

  <script type="text/javascript">
    lsImageData = <%= raw @image.js_serialize.to_json %>;
  </script>
<% end %>

<h1>Update your image</h1>

<%= render 'form' %>

<%= link_to 'Back to your images', images_user_path %>

app/views/images/featured.html.erb
<% content_for :head do %>
  <%= javascript_include_tag :images_gallery %>
  <%= stylesheet_link_tag 'images/gallery', :media => 'all' %>
<% end %>

<h2>Featured LifeSize images</h2>

<%= link_to 'Recently added LifeSize images', images_recent_path %>

<% if @images.nil? || @images.empty? %>
<p>There aren't any featured images</p>
<% else %>

<div id="container">
  <% for image in @images %>
    <%= render :partial => 'image_tile', :locals => { :image => image, :compact => true, :product_images => false } %>
  <% end %>
</div>
<!-- distance_of_time_in_words(Time.now, image.created_at) -->

<% end %>

<br />

<%= link_to 'Add your own LifeSize image', new_image_path, :class => 'big-link' %>

app/views/images/index.html.erb
<% content_for :added_scripts do %>
<%= javascript_include_tag 'ls/lifesizer' %>
<% end %>

<% content_for :script_content do %>

//  $.pollScreen(0,0, function(w,h){alert("new dim " + w + "x" + h);});

// make thumbnails lifesizeable
lifesizer({ account: "1",
            host: "<%= current_host %>"
          });

$(function() {
  //$('td').tooltip();
});

<% end %>



<h1>Your images</h1>

<% if @images.nil? %>
<p>You don't have any images yet</p>
<% else %>

<table>

<% for image in @images %>
  <tr>
    <td class="col_thumbnail"><%= thumbnail(image) %></td>
    <td class="col_name">
      <div class="image_name"><%= image.name %></div>
	  <div class="image_description"><%= image.description %></div>
	</td>
    <td class="col_dimensions">
      <%= image.width %>x<%= image.height %><br/>
	  <%= image.ppi %> ppi
	</td>
    <td><!-- %= link_to 'Show', user_image_path(image.user, image) %><br/-->
        <!-- %= link_to 'Edit', edit_user_image_path(image.user, image) %><br/-->
        <%= button_to "Delete", image_path(image), :method=>:delete, :class=>:destroy, :confirm=>"Are you sure?" %>
    </td>
  </tr>
<% end %>
</table>

<% end %>

<br />

<%= link_to 'Add an image', images_add_image_path %>

app/views/images/new.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'images/new' %>
  <%= stylesheet_link_tag 'images/new', :media => 'all' %>
<% end %>

<% title "Add a LifeSize image" %>

<% if @has_custom_bookmarklet %>
<h5>There'a a new and better way to add your images directly on <%= @api_key.hostname || 'your site' %>.<br/>
  <%= link_to 'Click here', account_bookmarklet_path %> to view instructions.
</h5><br/>
<% end %>

<h2>Add a LifeSize image</h2>

<%= form_for @image, :html => {:multipart => true, :class => 'lsform'} do |f| %>

  <%= render :partial => 'layouts/alert', :object => f.error_messages(:header_message => "Oops, That didn't work.", :header_tag => :h2,
        :message => "You'll need to fix the following input fields:") if !f.error_messages.blank? %>

  <div id="upload_section">

    <div id="upload_url">
      <span>Direct url to the image (jpg or png) to add to LifeSizer</span><br/>
      <%= f.text_field :remote_upload_url, :size => nil %>
    </div>
    <div id="or">-OR-</div>

    <div id="upload_file">
      <span>if your image is not yet on the web, you can upload it here. &nbsp; <a href="#" class="suggest_tooltip">what makes a good LifeSize image?</a></span><br/>
      <%= f.file_field :upload %>
      <%= f.hidden_field :upload_cache %>
    </div>

  </div>

  <div id="name_section">
    <span><%= f.label :name, "Title" %> (optional) &nbsp; <img id="help" class="title_tooltip help_icon" src="/images/icons/question-mark.png"></span><br/>
    <%= f.text_field :name, :size => nil %>
  </div>

  <div id="page_url_section">
    <span><%= f.label :page_url, "Page URL" %> (optional) &nbsp; <img id="help" class="page_url_tooltip help_icon" src="/images/icons/question-mark.png"></span><br/>
    <%= f.text_field :page_url, :size => nil %>
  </div>

  <div id="ref_section">
    <span><%= f.label :ref, "Reference" %> (optional) &nbsp; <img class="ref_tooltip help_icon" src="/images/icons/question-mark.png"></span><br/>
    <%= f.text_field :ref, :size => nil %>
  </div>

  <%= f.hidden_field :width %>
  <%= f.hidden_field :height %>
  <%= f.hidden_field :medium_width %>
  <%= f.hidden_field :medium_height %>
  <%= f.hidden_field :original_url %>
  <input type="hidden" name="browser_width" value="0" />
  <input type="hidden" name="browser_height" value="0" />

  <%= f.submit 'next', :class => 'blue-button' %>  <%= image_tag("/images/spinner.gif", :height => '31', :width => '31', :id => 'spinner' ) %>

<% end %>

app/views/images/recent.html.erb
<% content_for :head do %>
  <%= javascript_include_tag :images_gallery %>
  <%= stylesheet_link_tag 'images/gallery', :media => 'all' %>
<% end %>

<h2>Recently added images</h2>

<%= link_to 'See featured images', images_featured_path %>

<% if @images.nil? || @images.empty? %>
<p>No images</p>
<% else %>

    <div id="container">
      <% for image in @images %>
        <%= render :partial => 'image_tile', :locals => { :image => image, :compact => true, :product_images => false } %>
      <% end %>
    </div>

    <nav id="page-nav">
      <a href="<%= next_page_url %>">next page</a>
    </nav>

<% end %>

<br />

<%= link_to 'Add your own LifeSize image', new_image_path, :class => 'big-link' %>

app/views/images/user.html.erb
<% content_for :head do %>
  <%= javascript_include_tag :images_gallery %>
  <%= stylesheet_link_tag 'images/gallery', :media => 'all' %>
<% end %>

<% title "Your LifeSizer images" %>

<h2>Your LifeSizer images</h2>

<% if @images.empty? %>
<p>You haven't added any images yet</p>
<% else %>

<div id="wide-layout">

<div id="container">
  <% for image in @images %>
    <%= render :partial => 'image_tile', :locals => { :image => image, :compact => false, :product_images => true } %>
  <% end %>

  <nav id="page-nav">
    <a href="<%= next_page_url %>">next page</a>
  </nav>
</div>

</div><!-- end wide layout -->

<% end %>

<br />

<%= link_to 'Add a LifeSize image', new_image_path %>